kubecost/kubectl-cost

- Makefile
Required because Krew CI requires a LICENSE in the release archive.
> Add LICENSE to release .tar.gz

- README.md
- pkg/cmd/common.go
The window parameter in the CLI is equivalent to the
window parameter in the Kubecost APIs. This makes that
more clear in the README and `--help`.
> Add a link to detailed window parameter docs

- pkg/query/aggapi.go
- pkg/query/allocation.go
This will provide immense help with debugging. Previously, users
simply received a "request failed" message with no useful information.
Now we will see actual API response data.
Tested locally with a known previous failure case: `kubectl cost namespace` with no data available for `yesterday` without `etl=true` (introduced in https://github.com/kubecost/kubectl-cost/pull/60). In that case, the error message from the API is displayed.
> Show response data when requests fail

- README.md
- go.mod
- go.sum
- pkg/cmd/common.go
- pkg/cmd/controller.go
- pkg/cmd/deployment.go
- pkg/cmd/label.go
- pkg/cmd/namespace.go
- pkg/cmd/pod.go
- pkg/query/aggapi.go
- pkg/query/allocation.go
- pkg/query/portforward.go
Multiple users have reported problems with kubectl cost
when running in a more security conscious environment that
implements network security policies of various kinds. These
policies often prevent the K8s API server from communicating
with the Kubecost service.
This commit introduces new behavior that will cause requests,
by default, to go through a temporarily forwarded port on
localhost that goes to a Kubecost pod. This entirely circumvents
the issue of API server proxying, but is more complex.
The old behavior is now under the flag --use-proxy.
Tested locally against a GKE cluster.
> Use port forwarding instead of API server proxying

- pkg/cmd/controller.go
- pkg/cmd/cost.go
- pkg/cmd/deployment.go
- pkg/cmd/label.go
- pkg/cmd/namespace.go
- pkg/cmd/pod.go
- pkg/cmd/tui.go
- pkg/query/aggapi.go
- pkg/query/allocation.go
- pkg/query/config.go
Necessary because #80 didn't fix the permission problem -- the currency code request was still going through the API server proxy method.
Also includes refactors to stop duplicating query code.
Tested locally against a GKE cluster.
> QueryCurrencyCode can port forward

- README.md
- pkg/cmd/common.go
While "yesterday" is technically the most correct way to query
exactly 1 day of data right now, it shows unexpected empty
responses for users who have just installed Kubecost and have
no data for yesterday. This introduces a better default experience
for new users.
I chose `1d` instead of `today` because `today` can seriously underreport if the time is just after UTC midnight. `1d` will likely slightly overreport but that overreporting is temporary and will be automatically resolved by the release and deployment of hourly ETL.
> Change default window to 1d

- pkg/cmd/common.go
- pkg/cmd/output.go
As described in https://github.com/kubecost/kubectl-cost/issues/85.
Tested this locally with https://github.com/kubecost/docs/blob/master/kubecost-lb.yaml, which seems to work.
> Add "show-lb" flag for displaying Load Balancer Cost in "--historical" queries.

- README.md
- pkg/cmd/common.go
- pkg/cmd/controller.go
- pkg/cmd/cost.go
- pkg/cmd/deployment.go
- pkg/cmd/label.go
- pkg/cmd/namespace.go
- pkg/cmd/node.go
- pkg/cmd/output.go
- pkg/cmd/pod.go
- pkg/cmd/tui.go
- pkg/query/allocation.go
- pkg/query/assetsapi.go
Ref https://github.com/kubecost/kubectl-cost/issues/78.
Adds node subcommand which generates a cost table filtered by individual nodes. Also implements `QueryAssets` and `writeAssetTable` which can be modified to be used for other asset types in the future.
Sample output:
```kubectl cost node --show-ram --show-type --historical --show-cpu
+-------------+---------------------------------------------+------------+--------------+--------------+--------------+
| CLUSTER     | NAME                                        | ASSET TYPE | CPU COST     | RAM COST     | TOTAL COST   |
+-------------+---------------------------------------------+------------+--------------+--------------+--------------+
| cluster-one | gke-test-cluster-pool-1-9bb98ef8-cf3j       | e2-medium  |     0.540200 | …
```
> Add node subcommand

- pkg/cmd/cost.go
It was sometimes unclear that Kubecost has to be installed in the target
cluster for kubectl-cost to function. This commit adds two things to
`kubectl cost help`:
- clarification of the need for Kubecost to be installed
- a pre-formatted Helm install for Kubecost!
N/A
Improved help information (with Kubecost install instructions) when running `kubectl cost help`
- N/A
Locally by running `kubectl cost help` and checking the output!
N/A
> Add long explanation, with install instructions

- .github/workflows/build-release.yaml
Installing with `go get` is now deprecated, so we have to use `go install`
in the build-release workflow instead.
N/A
N/A
N/A
Locally with `act` (https://github.com/nektos/act) through the `go install` step. This is the step that failed in https://github.com/kubecost/kubectl-cost/actions/runs/2265123192.
N/A
> Fix govvv install step in build-release workflow

- pkg/cmd/deployment.go
- pkg/cmd/namespace.go
- pkg/cmd/node.go
- pkg/cmd/pod.go
Signed-off-by: Anurag <contact.anurag7@gmail.com>
- This PR adds the aliases mentioned in #108 
- Aliases match the short names present in `kubectl api-resources` 
- No
- This will save some time as one will avoid extra typing
- #108 
- https://kubecost.zendesk.com/agent/tickets/1956
Closes #108 
- I have tested this PR locally on my k3s cluster
- No
> add aliases for k8s resources

- pkg/query/podutil.go
- pkg/query/portforward.go
Tested on a cluster with spot nodes, which causes the
kubecost-cost-analyzer pod to occasionally die in a Completed state,
which cannot serve requests. This change makes kubectl-cost
work correctly in that environment.
- kubectl cost will only port-forward to Pods in a Ready state. Previously, kubectl cost could fail with a panic if the first cost-analyzer pod listed by the equivalent of `kubectl get pods` was in a non-Ready state (like Error or Completed).
Against a cluster with cost-analyzer pods in a Completed state. Before the change, `kubectl cost` panicked. Afterward, it functions correctly.
> Only port-forward to Ready Pods

- README.md
- pkg/cmd/common.go
Currently to use proxy Kubectl-cost uses --use-proxy flag, there's a proposal to assign it via environment variable KUBECTL_COST_USE_PROXY describe in the linked issue #107 , this is the code for this.
No
There will be no support to use proxy via --use-proxy flag to the CLI of kubectl-cost, going forward it will be assigned through the flag KUBECTL_COST_USE_PROXY.
- https://github.com/kubecost/kubectl-cost/issues/107
Test case 1. Did not create an environment variable and debugged to see that the options.UseProxy is assigned to false
Test case 2. create an environment variable $KUBECTL_COST_USE_PROXY=true and debugged to see that the options.UseProxy is assigned to true
Test case 3. create an environment variable $KUBECTL_COST_USE_PROXY=false and debugged to see that the options.UseProxy …
> adding environment variable KUBECTL_COST_USE_PROXY to set the --use-proxy behavior

- pkg/cmd/tui.go
Fixes the TUI always/almost always failing on startup with `ERR Allocation response was empty. Not updating the table.`
We were checking the wrong length, resulting in the TUI always failing
because the "allocations" is always initialized as empty. Updates the
naming of the query response variable for additional clarity in the
future.
Fixes the TUI always/almost always failing on startup with `ERR Allocation response was empty. Not updating the table.`
Against a 1.96.0 Kubecost running in GKE. Observed failure before change and success after change.
> Fix TUI allocation query always reporting empty

- pkg/cmd/common.go
- pkg/cmd/tui.go
- pkg/query/options.go
Previously, a Kubecost install done like this:
```sh
helm upgrade "kubecost2" kubecost/cost-analyzer \
--namespace kubecost2 \
-i --create-namespace
```
Would be queried with kubectl cost like this: `kubectl cost namespace -N "kubecost2" --service-name "kubecost2-cost-analyzer"`
But now it can be queried more simply, like this: `kubectl cost namespace -r "kubecost2"`
Or, if the namespace doesn't match, like this: `kubectl cost namespace -r "kubecost2" -N "other-namespace"`
This is a substantial UX improvement, so users don't have to be aware of KC service name templating convention. The `--service-name` flag remains with the same behavior, if manual overrides are desired.
Improve query UX by adding the catch-all `--release-name` (`-r`) flag to handle templating of both Kubecost namespace …
> Improve UX for querying nonstandard KC deployments

- README.md
- pkg/cmd/aggregatedcommandbuilder.go
- pkg/cmd/common.go
- pkg/cmd/label.go
- pkg/cmd/node.go
- pkg/cmd/tui.go
- pkg/query/allocation.go
- pkg/query/assetsapi.go
- pkg/query/configapi.go
- pkg/query/options.go
- pkg/query/portforward.go
Shaves about half a second off of a regular kubectl cost namespace query and provides big time savings for multi-workload predictions. These savings should be linear with # of predictions because this avoids re-forwarding for every workload prediction.
- Improved performance for multiple port-forwarded queries by maintaining a single port-forward session rather than re-forwarding for each query.
Locally with `kubectl cost predict` and `kubectl cost namespace`, observing improved perf in both cases but particularly in `predict` due to its multi-query nature.
Also checked to make sure ports aren't being leaked after the run with `ss -peanut`. Saw ports sticking around for a little while. Learned about TCP `TIME_WAIT` via https://unix.stackexchange.com/questions/68311/why-does-it-take-up-to-s …
> Improve multi-query perf with long-running forward

- README.md
- go.sum
- pkg/cmd/common.go
- pkg/cmd/cost.go
- pkg/cmd/output.go
- pkg/cmd/predict.go
- pkg/query/options.go
- pkg/query/prediction.go
- test/integration.sh
- test/multi.yaml
- Introduce the new `kubectl cost predict` command which predicts the cost of workloads based on resource requests. Try it with `kubectl cost predict -f "deployment.yaml"` or `kubectl get deployment -n kube-system -o yaml | kubectl cost predict -f -`. Requires a Kubecost version >= v1.100.
- Requires https://github.com/kubecost/kubecost-cost-model/pull/1132
Locally, targeting an as-yet-unreleased API.
Yes, README updates for new and modified flags.
> Predict resource costs from spec: 'kubectl cost predict'

- pkg/cmd/output.go
- pkg/cmd/predict.go
- pkg/query/prediction.go
- test/multi.yaml
Adds support for GPU cost prediction for standard AMD, Intel, and NVIDIA GPU plugins.
- Builds on https://github.com/kubecost/kubectl-cost/pull/132
- Updates predict response schema from changes in https://github.com/kubecost/kubecost-cost-model/pull/1132
- Adds support in `kubectl cost predict` for GPU cost for standard AMD, Intel, and NVIDIA GPU plugins (`amd.com/gpu`, `gpu.intel.com/i915`, `nvidia.com/gpu`).
```
→ go run cmd/kubectl-cost/kubectl-cost.go predict -f ./test/multi.yaml --window '2h'
+-------------------------------+------+-------+-----+------------+------------+-------------+-------------+
| WORKLOAD                      | CPU  | MEM   | GPU | CPU/MO     | MEM/MO     | GPU/MO      | TOTAL/MO    |
+-------------------------------+------+-------+-----+------------+----------- …
```
> Add support for basic GPU cost prediction, support altered prediction API schema

- pkg/query/options.go
Refactor of query logic caused o.restConfig to always be nil. This commit fixes that by simply passing through the restConfig in the proxy query case.
Problem discovered by CI: https://github.com/kubecost/integration-ci-cd/actions/runs/4014159525/jobs/6906486306
- Fix panic when --use-proxy is true
Locally. Observed panic before change with `--use-proxy` and no panic after.
> Fix panic when --use-proxy is true

- README.md
- pkg/cmd/common.go
- pkg/cmd/cost.go
- pkg/cmd/output.go
- pkg/cmd/predict.go
- pkg/query/options.go
- pkg/query/portforward.go
- pkg/query/predictiondiff.go
- test/integration.sh
- test/multi.yaml
See release note. Diff behavior matches the current diff used by our new Admission Controller.
- Added basic cost diffing support to `kubectl cost predict`. The default behavior will attempt to match workload specs with existing workloads tracked by Kubecost and will calculate a cost diff based on resource request. Disable with `--no-diff`.
- Added a namespace to the `kubectl cost predict` workload name output. If a namespace is not set on a given workload, it will be inherited from your Kubeconfig context.
- Targeted a dev cluster and the nightly cluster using the updated `test/multi.yaml` file. Observed full cost diffs on dev cluster (KC deployed in nonstandard namespace) and a true diff on the nightly cluster, as expected.
```
→ go run cmd/kubectl-cost/kubectl-cost.go predict -f …
```
> Add support for cost difference in "predict" using new API

- Makefile
- Fix kubectl-cost crashing on systems without glibc by disabling CGO for all builds
- Closes https://github.com/kubecost/kubectl-cost/issues/147
Before
```
→ make build      
cd cmd/kubectl-cost && govvv build
→ ldd cmd/kubectl-cost/kubectl-cost 
linux-vdso.so.1 (0x00007fff9ada9000)
libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007fc0aa7a5000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007fc0aa5be000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fc0aa7cb000)
```
After
```
→ make build
cd cmd/kubectl-cost && CGO_ENABLED=0 govvv build
→ ldd cmd/kubectl-cost/kubectl-cost
not a dynamic executable
```
> Fix kubectl-cost crashing on systems without glibc by disabling CGO for all builds

- pkg/cmd/display/predict.go
- pkg/cmd/predict.go
See release note.
- Added `--show-total` and `--hide-diff` flags to `kubectl cost predict`. "Total" cost is the expected monthly cost of each workload if the new spec were applied to your cluster. "Diff" cost (the default) is the expected monthly cost _change_ of applying each new spec to your cluster.
https://kubecost.atlassian.net/browse/CORE-113
```
→ go run cmd/kubectl-cost/kubectl-cost.go predict -r michaelkc -f ./test/multi.yaml --show-total
OBJECT                      QTY  Δ QTY  RESOURCE UNIT   COST PER UNIT      COST/MO     Δ COST/MO    % CHANGE 
──────────────────────────────────────────────────────────────────────────────────────────────────────────────
default deployment            9  +8.97  CPU cores           23.08 USD   207.68 USD   +206.99 USD  +29900.00% 
nginx-deployment …
```
> Add --show-total to show full cost alongside diff and --hide-diff to hide diff info

- pkg/query/prediction_speccost.go
Remove content type header for /prediction/speccost calls
Backend no longer requires it, makes us flexible
for yaml and json
- Requires https://github.com/kubecost/kubecost-cost-model/pull/1916
Added JSON manifest support to `kubectl cost predict`
> Remove content type header for /prediction/speccost API calls

- README.md
Wrong URL to the OpenCost `kubectl cost` page
> Fixed OpenCost URL

- README.md
> Updates README.md to fix broken API link

- README.md
- pkg/query/options.go
This Pull Request adds the `--opencost` flag to the cost command to setup standard OpenCost configuration. It is essentially an alias for the following flags:
`--service-port 9003 --service-name opencost --kubecost-namespace opencost --allocation-path /allocation/compute`
N/A
The user will have the possibility to easily set OpenCost as the target service to the `kubectl cost` command by simply setting the `--opencost` instead of configuring the OpenCost default settings flag-by-flag.
- https://github.com/kubecost/kubectl-cost/issues/156
This Pull Request was tested in an Oracle Kubernetes Engine (OKE)-based Kubernetes cluster configured with OpenCost and identical behaviour with providing the following flags was asserted:
`--service-port 9003 --service-name opencost --kubecost-namespace …
> Add `--opencost` flag to setup standard OpenCost configuration

- go.mod
- go.sum
Bump oauth2 to v0.28.0 to eliminate CVE
No
Bump oauth2 to v0.28.0 to eliminate CVE
N/A
It wasn't. Hoping that opening this PR runs some test automation.
No.
> Bump oauth2 to v0.28.0 to eliminate CVE
